
"use client";

import { useState, useRef, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
  CardFooter,
} from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
  DialogDescription,
  DialogFooter,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Flame, Beef, Wheat, Fish, GlassWater, Upload, Sparkles, Loader2, Salad, X, Star, Dumbbell, Lightbulb } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import { analyzeMeal, AnalyzeMealOutput } from "@/ai/flows/analyze-meal";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { recentWorkouts } from "@/lib/data";
import { getPostWorkoutNutritionAdvice } from "@/ai/flows/get-post-workout-nutrition-advice";
import { getNutritionInsight } from "@/ai/flows/get-nutrition-insight";


const initialNutritionData = {
  calories: {
    label: "Calories",
    current: 1850,
    target: 2500,
    unit: "kcal",
    icon: Flame,
  },
  protein: {
    label: "Protein",
    current: 120,
    target: 150,
    unit: "g",
    icon: Beef,
  },
  carbs: {
    label: "Carbohydrates",
    current: 200,
    target: 300,
    unit: "g",
    icon: Wheat,
  },
  fats: {
    label: "Fats",
    current: 60,
    target: 70,
    unit: "g",
    icon: Fish,
  },
  water: {
    label: "Water",
    current: 1.5,
    target: 2.5,
    unit: "L",
    icon: GlassWater,
  },
};

export default function NutritionPage() {
  const [nutrition, setNutrition] = useState(initialNutritionData);
  const { toast } = useToast();

  const handleLogMeal = (mealData: AnalyzeMealOutput) => {
    setNutrition(prev => ({
        ...prev,
        calories: { ...prev.calories, current: prev.calories.current + mealData.calories },
        protein: { ...prev.protein, current: prev.protein.current + mealData.protein },
        carbs: { ...prev.carbs, current: prev.carbs.current + mealData.carbs },
        fats: { ...prev.fats, current: prev.fats.current + mealData.fats },
    }));
    toast({
        title: "Meal Logged!",
        description: `${mealData.description} has been added to your daily log.`
    })
  };


  return (
    <div className="space-y-6">
      <Card>
        <CardHeader className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <CardTitle className="font-headline">Daily Nutrition</CardTitle>
            <CardDescription>Your intake for today.</CardDescription>
          </div>
          <LogMealDialog onLogMeal={handleLogMeal} />
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {Object.values(nutrition).map((item) => (
            <Card key={item.label}>
              <CardHeader className="flex flex-row items-center justify-between pb-2">
                <CardTitle className="text-sm font-medium">
                  {item.label}
                </CardTitle>
                <item.icon className="h-4 w-4 text-muted-foreground" />
              </CardHeader>
              <CardContent>
                <div className="text-2xl font-bold font-headline">
                  {item.current}
                  <span className="text-sm font-normal text-muted-foreground">
                    {" "}/ {item.target} {item.unit}
                  </span>
                </div>
                <Progress
                  value={(item.current / item.target) * 100}
                  className="mt-2 h-2"
                  aria-label={`${item.label} intake`}
                />
              </CardContent>
            </Card>
          ))}
        </CardContent>
      </Card>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <PostWorkoutAdvisor />
        <AiInsights />
      </div>

       <Card>
            <CardHeader>
                <CardTitle className="font-headline">Advanced Nutrition Tools</CardTitle>
                <CardDescription>Unlock powerful AI features to help you reach your goals faster.</CardDescription>
            </CardHeader>
            <CardContent>
                <p>Get supplement suggestions, recipe recommendations, and meal prep shopping lists all generated by AI.</p>
            </CardContent>
            <CardFooter>
                <Button asChild>
                    <Link href="/nutrition-tools">
                        <Star className="mr-2 h-4 w-4" />
                        Access Advanced Tools
                    </Link>
                </Button>
            </CardFooter>
        </Card>

    </div>
  );
}

function LogMealDialog({ onLogMeal }: { onLogMeal: (data: AnalyzeMealOutput) => void }) {
  const [open, setOpen] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  const [imagePreview, setImagePreview] = useState<string | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [analysisResult, setAnalysisResult] = useState<AnalyzeMealOutput | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();

  useEffect(() => {
    return () => {
      if (imagePreview) {
        URL.revokeObjectURL(imagePreview);
      }
    };
  }, [imagePreview]);

  const resetState = () => {
    setImageFile(null);
    setImagePreview(null);
    setIsLoading(false);
    setAnalysisResult(null);
  };

  const handleFileChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    resetState();
    const file = event.target.files?.[0];
    if (file) {
      if (file.size > 5 * 1024 * 1024) {
        toast({
          variant: "destructive",
          title: "File too large",
          description: "Please upload an image smaller than 5MB.",
        });
        return;
      }
      setImageFile(file);
      const previewUrl = URL.createObjectURL(file);
      setImagePreview(previewUrl);
    }
  };

  const handleAnalyzeMeal = async () => {
    if (!imageFile) {
      toast({
        variant: "destructive",
        title: "No Image Selected",
        description: "Please choose an image of your meal to analyze.",
      });
      return;
    }

    setIsLoading(true);
    setAnalysisResult(null);

    try {
      const base64data = await new Promise<string>((resolve, reject) => {
        const reader = new FileReader();
        reader.readAsDataURL(imageFile);
        reader.onload = () => resolve(reader.result as string);
        reader.onerror = (error) => reject(error);
      });

      const result = await analyzeMeal({ imageDataUri: base64data });
      setAnalysisResult(result);
    } catch (error) {
      console.error(error);
      toast({
        variant: "destructive",
        title: "Analysis Failed",
        description: "Could not analyze the meal image. Please try again.",
      });
    } finally {
      setIsLoading(false);
    }
  };

  const handleAddToLog = () => {
    if (analysisResult) {
      onLogMeal(analysisResult);
      setOpen(false);
    }
  }

  return (
    <Dialog open={open} onOpenChange={(isOpen) => {
        setOpen(isOpen);
        if (!isOpen) resetState();
    }}>
      <DialogTrigger asChild>
        <Button>
          <Salad className="mr-2" /> Log Meal with AI
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="font-headline">Log a Meal with AI</DialogTitle>
          <DialogDescription>
            Upload a photo of your meal and our AI will analyze its nutritional content.
          </DialogDescription>
        </DialogHeader>
        <div className="space-y-4">
          <Input
            id="meal-image"
            type="file"
            accept="image/*"
            ref={fileInputRef}
            onChange={handleFileChange}
            className="hidden"
          />
          {imagePreview ? (
            <div className="relative group">
              <Image src={imagePreview} alt="Meal preview" width={400} height={300} className="rounded-md w-full object-cover aspect-video" />
               <Button variant="destructive" size="icon" className="absolute top-2 right-2 opacity-0 group-hover:opacity-100 transition-opacity" onClick={() => {
                  setImageFile(null);
                  setImagePreview(null);
                  setAnalysisResult(null);
                  if(fileInputRef.current) fileInputRef.current.value = "";
               }}>
                  <X className="h-4 w-4" />
               </Button>
            </div>
          ) : (
             <Button
              variant="outline"
              className="w-full flex flex-col h-32 items-center justify-center gap-2 border-dashed"
              onClick={() => fileInputRef.current?.click()}
            >
              <Upload className="h-8 w-8 text-muted-foreground" />
              <span className="text-muted-foreground">Click to upload an image</span>
            </Button>
          )}

          {isLoading ? (
            <div className="flex items-center justify-center text-muted-foreground p-4">
              <Loader2 className="mr-2 h-5 w-5 animate-spin" />
              Analyzing your meal...
            </div>
          ) : analysisResult ? (
            <Alert>
              <Sparkles className="h-4 w-4" />
              <AlertTitle className="font-headline">AI Analysis Complete</AlertTitle>
              <AlertDescription>
                <p className="font-semibold mb-2">{analysisResult.description}</p>
                <div className="grid grid-cols-2 gap-x-4 gap-y-1 text-sm">
                  <span><Flame className="inline mr-1 h-4 w-4"/>Calories:</span> <span className="font-medium text-right">{analysisResult.calories} kcal</span>
                  <span><Beef className="inline mr-1 h-4 w-4"/>Protein:</span> <span className="font-medium text-right">{analysisResult.protein} g</span>
                  <span><Wheat className="inline mr-1 h-4 w-4"/>Carbs:</span> <span className="font-medium text-right">{analysisResult.carbs} g</span>
                  <span><Fish className="inline mr-1 h-4 w-4"/>Fats:</span> <span className="font-medium text-right">{analysisResult.fats} g</span>
                </div>
              </AlertDescription>
            </Alert>
          ) : null}
        </div>
        <DialogFooter>
          {analysisResult ? (
             <Button type="button" onClick={handleAddToLog} className="w-full">Add to Daily Log</Button>
          ) : (
            <Button type="button" onClick={handleAnalyzeMeal} disabled={isLoading || !imageFile} className="w-full">
              {isLoading ? 'Analyzing...' : 'Analyze Meal'}
              <Sparkles className="ml-2 h-4 w-4" />
            </Button>
          )}
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}

function PostWorkoutAdvisor() {
    const [advice, setAdvice] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const { toast } = useToast();

    const lastWorkout = recentWorkouts[0];

    const handleGetAdvice = async () => {
        setIsLoading(true);
        setAdvice(null);
        try {
            const result = await getPostWorkoutNutritionAdvice({ workoutType: lastWorkout.type });
            setAdvice(result.advice);
        } catch (error) {
            console.error(error);
            toast({
                variant: 'destructive',
                title: 'Failed to get advice',
                description: 'Could not get post-workout advice from AI. Please try again.',
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle className="font-headline">Post-Workout AI Advisor</CardTitle>
                <CardDescription>Get nutrition tips based on your last workout.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="flex items-center gap-4 rounded-md border p-3">
                    <Dumbbell className="h-6 w-6 text-primary" />
                    <div>
                        <p className="text-sm text-muted-foreground">Last workout</p>
                        <p className="font-semibold">{lastWorkout.type}</p>
                    </div>
                </div>
                
                {isLoading ? (
                     <div className="flex items-center justify-center text-muted-foreground p-4">
                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                        Generating tip...
                    </div>
                ) : advice ? (
                    <Alert>
                        <Sparkles className="h-4 w-4"/>
                        <AlertTitle className="font-semibold">AI Nutrition Tip</AlertTitle>
                        <AlertDescription>{advice}</AlertDescription>
                    </Alert>
                ) : null}

            </CardContent>
            <CardFooter>
                 <Button onClick={handleGetAdvice} disabled={isLoading} className="w-full">
                    {isLoading ? <Loader2 className="mr-2 animate-spin" /> : <Sparkles className="mr-2" />}
                    Get AI Advice
                </Button>
            </CardFooter>
        </Card>
    );
}

function AiInsights() {
    const [insight, setInsight] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const { toast } = useToast();

    const handleGetInsight = async () => {
        setIsLoading(true);
        setInsight(null);
        try {
            const result = await getNutritionInsight({ insightType: 'random' });
            setInsight(result.insight);
        } catch (error) {
            console.error(error);
            toast({
                variant: 'destructive',
                title: 'Failed to get insight',
                description: 'Could not get an AI insight. Please try again.',
            });
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <Card>
            <CardHeader>
                <CardTitle className="font-headline">AI Insights & Recommendations</CardTitle>
                <CardDescription>Get smart tips and reminders from your AI coach.</CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 min-h-[178px]">
               {isLoading ? (
                     <div className="flex items-center justify-center text-muted-foreground p-4">
                        <Loader2 className="mr-2 h-5 w-5 animate-spin" />
                        Generating insight...
                    </div>
                ) : insight ? (
                    <Alert>
                        <Lightbulb className="h-4 w-4"/>
                        <AlertTitle className="font-semibold">AI Insight</AlertTitle>
                        <AlertDescription>{insight}</AlertDescription>
                    </Alert>
                ) : (
                    <div className="text-center text-muted-foreground pt-4">
                        <p>Click the button to get a personalized nutrition tip from your AI coach.</p>
                    </div>
                )}
            </CardContent>
            <CardFooter>
                 <Button onClick={handleGetInsight} disabled={isLoading} className="w-full">
                    {isLoading ? <Loader2 className="mr-2 animate-spin" /> : <Lightbulb className="mr-2" />}
                    Get AI Insight
                </Button>
            </CardFooter>
        </Card>
    );
}
